"""initial schema

Revision ID: 01e33b3ee809
Revises: 
Create Date: 2026-09-24 00:04:21.257741
"""
from alembic import op
import sqlalchemy as sa


revision = '01e33b3ee809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('exclusive_booking', sa.Boolean(), nullable=False),
    sa.Column('require_booking_for_rfid', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_code'), 'labs', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'LAB_STAFF', 'ADMIN', name='role_enum', native_enum=False, length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_subject', sa.String(length=32), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'CHECKED_OUT', 'MAINTENANCE', 'RETIRED', name='asset_status_enum', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assets_lab_id'), 'assets', ['lab_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=48), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'COMPLETED', name='booking_status_enum', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_time < end_time', name='ck_booking_window'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_lab_window', 'bookings', ['lab_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_bookings_end_time'), 'bookings', ['end_time'], unique=False)
    op.create_index(op.f('ix_bookings_lab_id'), 'bookings', ['lab_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.Enum('MASTER_CONTROLLER', 'CAMERA', 'FACE_SERVER', 'SENSOR_NODE', name='device_type_enum', native_enum=False, length=48), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('door_closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_uid'), 'devices', ['device_uid'], unique=True)
    op.create_index(op.f('ix_devices_lab_id'), 'devices', ['lab_id'], unique=False)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_table('rfid_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_hex', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_credentials_uid_hex'), 'rfid_credentials', ['uid_hex'], unique=True)
    op.create_index(op.f('ix_rfid_credentials_user_id'), 'rfid_credentials', ['user_id'], unique=False)
    op.create_table('access_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('RFID', 'QR', 'FINGERPRINT', 'FACE', 'PORTAL', name='auth_method_enum', native_enum=False, length=48), nullable=False),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', 'PENDING', name='access_result_enum', native_enum=False, length=48), nullable=False),
    sa.Column('denial_reason', sa.Enum('TOKEN_UNKNOWN', 'TOKEN_REVOKED', 'BOOKING_NOT_CONFIRMED', 'BOOKING_CANCELLED', 'BOOKING_NOT_STARTED', 'BOOKING_EXPIRED', 'WRONG_LAB', 'USER_INACTIVE', 'UNKNOWN_CREDENTIAL', 'NO_ACTIVE_BOOKING', 'IDENTITY_MISMATCH', 'BIOMETRIC_TIMEOUT', 'BIOMETRIC_FAILED', 'DEVICE_UNKNOWN', 'BACKEND_UNAVAILABLE', name='denial_reason_enum', native_enum=False, length=48), nullable=True),
    sa.Column('credential_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_attempts_booking_id'), 'access_attempts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_access_attempts_created_at'), 'access_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_attempts_denial_reason'), 'access_attempts', ['denial_reason'], unique=False)
    op.create_index(op.f('ix_access_attempts_device_id'), 'access_attempts', ['device_id'], unique=False)
    op.create_index(op.f('ix_access_attempts_lab_id'), 'access_attempts', ['lab_id'], unique=False)
    op.create_index(op.f('ix_access_attempts_result'), 'access_attempts', ['result'], unique=False)
    op.create_index(op.f('ix_access_attempts_user_id'), 'access_attempts', ['user_id'], unique=False)
    op.create_index('ix_attempt_lab_time', 'access_attempts', ['lab_id', 'created_at'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'QR_GENERATED', 'QR_SCAN', 'QR_VALIDATED', 'QR_REJECTED', 'RFID_SCAN', 'RFID_ACCEPTED', 'RFID_REJECTED', 'FINGERPRINT_ATTEMPT', 'FINGERPRINT_ACCEPTED', 'FINGERPRINT_REJECTED', 'FACE_ATTEMPT', 'FACE_ACCEPTED', 'FACE_REJECTED', 'IDENTITY_MISMATCH', 'ACCESS_GRANTED', 'ACCESS_DENIED', 'DOOR_OPENED', 'DOOR_CLOSED', 'DEVICE_ONLINE', 'DEVICE_OFFLINE', 'ALARM', 'ASSET_CHECKOUT', 'ASSET_RETURN', name='event_type_enum', native_enum=False, length=48), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('RFID', 'QR', 'FINGERPRINT', 'FACE', 'PORTAL', name='auth_method_enum2', native_enum=False, length=48), nullable=True),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', 'PENDING', name='access_result_enum2', native_enum=False, length=48), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_events_booking_id'), 'access_events', ['booking_id'], unique=False)
    op.create_index(op.f('ix_access_events_created_at'), 'access_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_events_device_id'), 'access_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_access_events_event_type'), 'access_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_access_events_lab_id'), 'access_events', ['lab_id'], unique=False)
    op.create_index(op.f('ix_access_events_user_id'), 'access_events', ['user_id'], unique=False)
    op.create_index('ix_event_lab_time', 'access_events', ['lab_id', 'created_at'], unique=False)
    op.create_index('ix_event_type_time', 'access_events', ['event_type', 'created_at'], unique=False)
    op.create_table('access_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.Enum('RFID', 'QR', 'FINGERPRINT', 'FACE', 'PORTAL', name='auth_method_enum3', native_enum=False, length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_sessions_booking_id'), 'access_sessions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_access_sessions_ended_at'), 'access_sessions', ['ended_at'], unique=False)
    op.create_index(op.f('ix_access_sessions_lab_id'), 'access_sessions', ['lab_id'], unique=False)
    op.create_index(op.f('ix_access_sessions_started_at'), 'access_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_access_sessions_user_id'), 'access_sessions', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_lab_id'), 'alerts', ['lab_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('asset_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transactions_asset_id'), 'asset_transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_transactions_created_at'), 'asset_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_transactions_lab_id'), 'asset_transactions', ['lab_id'], unique=False)
    op.create_index(op.f('ix_asset_transactions_user_id'), 'asset_transactions', ['user_id'], unique=False)
    op.create_table('lab_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'device_id', name='uq_lab_device')
    )
    op.create_index(op.f('ix_lab_devices_device_id'), 'lab_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_lab_devices_lab_id'), 'lab_devices', ['lab_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_booking_id'), 'qr_tokens', ['booking_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_lab_id'), 'qr_tokens', ['lab_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_token'), 'qr_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_qr_tokens_user_id'), 'qr_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_valid_from'), 'qr_tokens', ['valid_from'], unique=False)
    op.create_index(op.f('ix_qr_tokens_valid_until'), 'qr_tokens', ['valid_until'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_lab_metric_time', 'sensor_readings', ['lab_id', 'metric', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_lab_id'), 'sensor_readings', ['lab_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_metric'), 'sensor_readings', ['metric'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_metric'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_lab_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_lab_metric_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_qr_tokens_valid_until'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_valid_from'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_user_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_token'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_lab_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_booking_id'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index(op.f('ix_lab_devices_lab_id'), table_name='lab_devices')
    op.drop_index(op.f('ix_lab_devices_device_id'), table_name='lab_devices')
    op.drop_table('lab_devices')
    op.drop_index(op.f('ix_asset_transactions_user_id'), table_name='asset_transactions')
    op.drop_index(op.f('ix_asset_transactions_lab_id'), table_name='asset_transactions')
    op.drop_index(op.f('ix_asset_transactions_created_at'), table_name='asset_transactions')
    op.drop_index(op.f('ix_asset_transactions_asset_id'), table_name='asset_transactions')
    op.drop_table('asset_transactions')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_lab_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_access_sessions_user_id'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_started_at'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_lab_id'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_ended_at'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_booking_id'), table_name='access_sessions')
    op.drop_table('access_sessions')
    op.drop_index('ix_event_type_time', table_name='access_events')
    op.drop_index('ix_event_lab_time', table_name='access_events')
    op.drop_index(op.f('ix_access_events_user_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_lab_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_event_type'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_device_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_created_at'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_booking_id'), table_name='access_events')
    op.drop_table('access_events')
    op.drop_index('ix_attempt_lab_time', table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_user_id'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_result'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_lab_id'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_device_id'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_denial_reason'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_created_at'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_booking_id'), table_name='access_attempts')
    op.drop_table('access_attempts')
    op.drop_index(op.f('ix_rfid_credentials_user_id'), table_name='rfid_credentials')
    op.drop_index(op.f('ix_rfid_credentials_uid_hex'), table_name='rfid_credentials')
    op.drop_table('rfid_credentials')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_lab_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_uid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_lab_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_time'), table_name='bookings')
    op.drop_index('ix_booking_lab_window', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_lab_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_labs_code'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
