"""lab catalogue and booking entry tracking

Revision ID: 392460921eaf
Revises: 01e33b3ee809
Create Date: 2026-09-24 02:46:46.913420
"""
from alembic import op
import sqlalchemy as sa


revision = '392460921eaf'
down_revision = '01e33b3ee809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('first_entry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('last_entry_at', sa.DateTime(timezone=True), nullable=True))
    # server_default is required, NOT optional: these columns are NOT NULL and
    # the database already contains rows. Without a default, PostgreSQL has no
    # value to put in the existing bookings and labs and the migration aborts.
    # The default is then dropped so future inserts must be explicit and the
    # application stays the single source of truth for new rows.
    op.add_column('bookings', sa.Column('entry_count', sa.Integer(),
                                        nullable=False, server_default='0'))
    op.add_column('labs', sa.Column('category', sa.String(length=64),
                                    nullable=False, server_default='General'))
    op.add_column('labs', sa.Column('has_controller', sa.Boolean(),
                                    nullable=False, server_default=sa.false()))

    op.alter_column('bookings', 'entry_count', server_default=None)
    op.alter_column('labs', 'category', server_default=None)
    op.alter_column('labs', 'has_controller', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'has_controller')
    op.drop_column('labs', 'category')
    op.drop_column('bookings', 'entry_count')
    op.drop_column('bookings', 'last_entry_at')
    op.drop_column('bookings', 'first_entry_at')
    # ### end Alembic commands ###
